### PR TITLE
Add getLanguage implementation to CodeMirror6Editor

### PR DESCRIPTION
**Pull request by meatballs**
Take advantage of the recent addition to CodeMirror: https://github.com/codemirror/language/commit/5ffd32d24edd568677dc0558d211d88492176131

### CODE REVIEW

**Review by glacambre — COMMENTED** [review]
Hi - sorry for the delay in reviewing this. I tried your PR on https://codemirror.net/ and it doesn't seem to work - `null` is returned and then Neovim incorrectly guesses that the filetype is shell. Have you been able to get this to work on https://codemirror.net/ ?

**Comment by meatballs** [comment]
I don't think the codemirror feature is implemented there yet.

**Comment by meatballs** [comment]
@s-cork has put together a demo of codemirror working with the lastest change at: https://codepen.io/s-cork/full/LYjygqd

You should see that `document.querySelector(".cm-content").dataset.language` will return "python" there.

**Comment by glacambre** [comment]
This codepen indeed seems to work! Thank you for looking into this. I'll merge your PR, update editor-adapter in Firenvim, merge a couple of other PRs and then publish a new release.

**Comment by glacambre** [comment]
@meatballs I've uploaded a new Firenvim release (0.2.14) that embeds your editor-adapter changes to the Chrome Web Store. Your change will be available once the chrome web store team has reviewed and published it :).

**Comment by meatballs** [comment]
Excellent! Thank you.

**Pull request merged**
