### PR TITLE
Add CodeMirror6Editor

### PR DESCRIPTION
**Pull request by meatballs**
First attempt at #6

### CODE REVIEW

**Review by glacambre — CHANGES_REQUESTED** [review]
Hi @meatballs, thanks again for the PR and sorry for the review delay. I had to perform a few modifications in order to get your PR to compile and it's able to retrieve the content of the CodeMirror6 instance on https://codemirror.net/ .
However, setting the content of the instance does not seem to work, instead the following error is printed in the console:
```
Error: Permission denied to access property "selection" codemirror.js:1:46553
```

I can't remember from the top of my head if I've seen this kind of error before, so I'm not sure how to fix it.

If you want to test your editor-adapter changes with Firenvim, here's how I did it:
- Clone firenvim and build it with `npm run build`
- Delete `node_modules/editor-adapter`
- Create a symbolic link from your editor-adapter repo to firenvim's node_modules, e.g. `ln -s /path/to/editor-adapter firenvim/node_modules/editor-adapter`
- Then, re-build firenvim and load it in your browser as described here: https://github.com/glacambre/firenvim/blob/master/CONTRIBUTING.md#installing-the-addon

Sorry I can't spend more time investigating this (and sorry I force-pushed your PR, I noticed that retrieving the editor's content worked fine, pushed thinking the PR was ready and only then thought about testing writing to the page :facepalm: ). Please don't hesitate to ask any question you may have :) .

**Comment by meatballs** [comment]
I get an error when trying to build:
```
[webpack-cli] Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/home/owen/projects/personal/firenvim/node_modules/webpack/lib/util/createHash.js:155:18)
    at BulkUpdateDecorator.digest (/home/owen/projects/personal/firenvim/node_modules/webpack/lib/util/createHash.js:80:21)
    at /home/owen/projects/personal/firenvim/node_modules/webpack/lib/DefinePlugin.js:595:38
    at _next27 (eval at create (/home/owen/projects/personal/firenvim/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:44:1)
    at _next5 (eval at create (/home/owen/projects/personal/firenvim/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:97:1)
    at Hook.eval [as call] (eval at create (/home/owen/projects/personal/firenvim/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:111:1)
    at Hook.CALL_DELEGATE [as _call] (/home/owen/projects/personal/firenvim/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/home/owen/projects/personal/firenvim/node_modules/webpack/lib/Compiler.js:1053:26) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

Building with docker works fine.

**Comment by meatballs** [comment]
build issue fixed with NODE_OPTIONS as per this SO question: https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported

**Comment by meatballs** [comment]
and it's working fine for me - vivaldi browser, in case that makes any difference

**Comment by glacambre** [comment]
Oh, indeed, it does seem to work in chrome-based browser, it's only Firefox that doesn't work :thinking: .

**Comment by glacambre** [comment]
You did the work to get CodeMirror6 to work for your usecase, I won't force you to make it work for other people. I've added a commit that makes CodeMirror6 optional and will make Firenvim enable it when running in Chrome.

Thanks again for your contribution! :)

**Comment by meatballs** [comment]
Thank you! That gers my workflow back how I like it!

I have an idea for getting the language out of codemirror 6. I'll try it out today and submit a PR if it works out.

**Pull request merged**
